[package]
name = "bdcrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proj = '0.27.0'
geo = '0.23.0'
shapefile = {version = "0.3.0", features = ["geo-types"]}
geojson = '*'
zip = '*'
